version: '2'
services:
    jhipstercassandrasampleapplication-app:
        image: jhipstercassandrasampleapplication
        external_links:
            - jhipstercassandrasampleapplication-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    jhipstercassandrasampleapplication-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jhipstercassandrasampleapplication-cassandra
    jhipstercassandrasampleapplication-cassandra-node:
        image: cassandra:3.9
        links:
            - jhipstercassandrasampleapplication-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    jhipstercassandrasampleapplication-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstercassandrasampleapplication-cassandra-migration
        links:
            - jhipstercassandrasampleapplication-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
