version: '2'
services:
  jhipstercassandrasampleapplication-app:
    image: jhipstercassandrasampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jhipstercassandrasampleapplication-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstercassandrasampleapplication-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: jhipstercassandrasampleapplication-cassandra
  jhipstercassandrasampleapplication-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=jhipstercassandrasampleapplication-cassandra
  jhipstercassandrasampleapplication-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: jhipstercassandrasampleapplication-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
