version: '2'
services:
    jhipstercassandrasampleapplication-cassandra:
        container_name: jhipstercassandrasampleapplication-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/jhipsterCassandraSampleApplication/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    jhipstercassandrasampleapplication-cassandra-node:
        image: cassandra:2.2.7
        links:
            - jhipstercassandrasampleapplication-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    jhipstercassandrasampleapplication-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstercassandrasampleapplication-cassandra-migration
        links:
            - jhipstercassandrasampleapplication-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
